/*
 * Introduction to Functional Programming with Java
 * 
 * https://github.com/egalli64/jafun
 */
package com.example.jafun.m1.s7.rec;

import java.util.Collection;
import java.util.TreeSet;
import java.util.function.Supplier;

/**
 * HOF, lambda and record working together to generate a collection
 */
public class DogsGenerator {
    private static Dog[] dogs = { new Dog("Tom"), new Dog("Bob"), new Dog("Kim"), new Dog("Wim") };

    /**
     * A HOF that gets a supplier by functional interface, and add to it a few
     * record objects
     * 
     * @param supplier a dog collection
     * @return the populated collection
     */
    public static Collection<Dog> get(Supplier<Collection<Dog>> supplier) {
        Collection<Dog> result = supplier.get();
        for (Dog dog : dogs) {
            result.add(dog);
        }

        return result;
    }

    /**
     * Get a dog populated collection from the DogsGenerator::get HOF. The actual
     * collection object is generated by the passed lambda. Then, print the dog
     * records
     * 
     * @param args not used
     */
    public static void main(String[] args) {
        Collection<Dog> sortedDogs = DogsGenerator.get(TreeSet::new);
        System.out.println("Record dogs " + sortedDogs);
    }
}
